## MDAnalysis Tutorial - CECAM Workshop Jülich

* Part 1: David Dotson
* break (10:30 ish)
* Part 2: Oliver Beckstein
* Part 3: David Dotson presents: [MDSynthesis](https://github.com/Becksteinlab/MDSynthesis)

[Live notebook link](https://github.com/dotsdl/MDAnalysis-workshop-notebook-julich/blob/master/MDAnalysis%20Tutorial.ipynb): updates (and if not, remind presenter)

Try these:

In [2]:
import matplotlib.pyplot as plt
import MDAnalysis as mda

Live notebook is here: https://github.com/dotsdl/MDAnalysis-workshop-notebook-julich/blob/master/MDAnalysis%20Tutorial.ipynb

In [9]:
top = 'equilibrium/adk4AKE.psf'
u = mda.Universe(top)

In [10]:
u

<Universe with 3341 atoms and 3365 bonds>

In [12]:
u.atoms.indices

array([   0,    1,    2, ..., 3338, 3339, 3340])

In [13]:
u.atoms.names

array(['N', 'HT1', 'HT2', ..., 'CA', 'HA1', 'HA2'], 
      dtype='|S4')

In [14]:
u.atoms.resnames

array(['MET', 'MET', 'MET', ..., 'GLY', 'GLY', 'GLY'], 
      dtype='|S3')

In [15]:
u.atoms.resids

array([  1,   1,   1, ..., 214, 214, 214])

In [16]:
u.atoms.charges

array([-0.3 ,  0.33,  0.33, ..., -0.02,  0.09,  0.09])

In [17]:
u.atoms.masses

array([ 14.007,   1.008,   1.008, ...,  12.011,   1.008,   1.008])

In [18]:
u.atoms.types

array(['NH3', 'HC', 'HC', ..., 'CT2', 'HB', 'HB'], 
      dtype='|S4')

In [22]:
u.atoms.masses[2:11]

array([  1.008,   1.008,  12.011,   1.008,  12.011,   1.008,   1.008,
        12.011,   1.008])

In [24]:
u.atoms[2:11].masses

array([  1.008,   1.008,  12.011,   1.008,  12.011,   1.008,   1.008,
        12.011,   1.008])

In [25]:
ag = u.atoms[[2, 21, 2, -2]]

In [27]:
ag.indices

array([   2,   21,    2, 3339])

In [28]:
u.atoms[::3]

<AtomGroup with 1114 atoms>

In [30]:
u.atoms[u.atoms.masses < 10]

<AtomGroup with 1685 atoms>

In [33]:
u.atoms[(u.atoms.masses < 10) & (u.atoms.resnames == 'ARG')].names

array(['HN', 'HA', 'HB1', 'HB2', 'HG1', 'HG2', 'HD1', 'HD2', 'HE', 'HH11',
       'HH12', 'HH21', 'HH22', 'HN', 'HA', 'HB1', 'HB2', 'HG1', 'HG2',
       'HD1', 'HD2', 'HE', 'HH11', 'HH12', 'HH21', 'HH22', 'HN', 'HA',
       'HB1', 'HB2', 'HG1', 'HG2', 'HD1', 'HD2', 'HE', 'HH11', 'HH12',
       'HH21', 'HH22', 'HN', 'HA', 'HB1', 'HB2', 'HG1', 'HG2', 'HD1',
       'HD2', 'HE', 'HH11', 'HH12', 'HH21', 'HH22', 'HN', 'HA', 'HB1',
       'HB2', 'HG1', 'HG2', 'HD1', 'HD2', 'HE', 'HH11', 'HH12', 'HH21',
       'HH22', 'HN', 'HA', 'HB1', 'HB2', 'HG1', 'HG2', 'HD1', 'HD2', 'HE',
       'HH11', 'HH12', 'HH21', 'HH22', 'HN', 'HA', 'HB1', 'HB2', 'HG1',
       'HG2', 'HD1', 'HD2', 'HE', 'HH11', 'HH12', 'HH21', 'HH22', 'HN',
       'HA', 'HB1', 'HB2', 'HG1', 'HG2', 'HD1', 'HD2', 'HE', 'HH11',
       'HH12', 'HH21', 'HH22', 'HN', 'HA', 'HB1', 'HB2', 'HG1', 'HG2',
       'HD1', 'HD2', 'HE', 'HH11', 'HH12', 'HH21', 'HH22', 'HN', 'HA',
       'HB1', 'HB2', 'HG1', 'HG2', 'HD1', 'HD2', 'HE', 'HH11', 'HH12'

## Working with individual atoms

In [34]:
a = u.atoms[0]

In [38]:
a.name

'N'

### Challenge: count the number of glycine residues in the protein.

In [41]:
r = u.atoms[u.atoms.resnames == 'GLY'].resids

In [42]:
r

array([  7,   7,   7,   7,   7,   7,   7,  10,  10,  10,  10,  10,  10,
        10,  12,  12,  12,  12,  12,  12,  12,  14,  14,  14,  14,  14,
        14,  14,  25,  25,  25,  25,  25,  25,  25,  32,  32,  32,  32,
        32,  32,  32,  42,  42,  42,  42,  42,  42,  42,  46,  46,  46,
        46,  46,  46,  46,  56,  56,  56,  56,  56,  56,  56,  80,  80,
        80,  80,  80,  80,  80,  85,  85,  85,  85,  85,  85,  85, 100,
       100, 100, 100, 100, 100, 100, 122, 122, 122, 122, 122, 122, 122,
       130, 130, 130, 130, 130, 130, 130, 144, 144, 144, 144, 144, 144,
       144, 150, 150, 150, 150, 150, 150, 150, 180, 180, 180, 180, 180,
       180, 180, 189, 189, 189, 189, 189, 189, 189, 198, 198, 198, 198,
       198, 198, 198, 214, 214, 214, 214, 214, 214, 214, 214])

In [43]:
import numpy as np

In [46]:
np.unique(r)

array([  7,  10,  12,  14,  25,  32,  42,  46,  56,  80,  85, 100, 122,
       130, 144, 150, 180, 189, 198, 214])

In [45]:
len(np.unique(r))

20

## ResidueGroups and SegmentGroups

In [47]:
u.residues

<ResidueGroup [<Residue MET, 1>, <Residue ARG, 2>, <Residue ILE, 3>, <Residue ILE, 4>, <Residue LEU, 5>, <Residue LEU, 6>, <Residue GLY, 7>, <Residue ALA, 8>, <Residue PRO, 9>, <Residue GLY, 10>, <Residue ALA, 11>, <Residue GLY, 12>, <Residue LYS, 13>, <Residue GLY, 14>, <Residue THR, 15>, <Residue GLN, 16>, <Residue ALA, 17>, <Residue GLN, 18>, <Residue PHE, 19>, <Residue ILE, 20>, <Residue MET, 21>, <Residue GLU, 22>, <Residue LYS, 23>, <Residue TYR, 24>, <Residue GLY, 25>, <Residue ILE, 26>, <Residue PRO, 27>, <Residue GLN, 28>, <Residue ILE, 29>, <Residue SER, 30>, <Residue THR, 31>, <Residue GLY, 32>, <Residue ASP, 33>, <Residue MET, 34>, <Residue LEU, 35>, <Residue ARG, 36>, <Residue ALA, 37>, <Residue ALA, 38>, <Residue VAL, 39>, <Residue LYS, 40>, <Residue SER, 41>, <Residue GLY, 42>, <Residue SER, 43>, <Residue GLU, 44>, <Residue LEU, 45>, <Residue GLY, 46>, <Residue LYS, 47>, <Residue GLN, 48>, <Residue ALA, 49>, <Residue LYS, 50>, <Residue ASP, 51>, <Residue ILE, 52>, <Resid

In [48]:
u.segments

<SegmentGroup [<Segment ADK>]>

In [49]:
u.residues.resnames

array(['MET', 'ARG', 'ILE', 'ILE', 'LEU', 'LEU', 'GLY', 'ALA', 'PRO',
       'GLY', 'ALA', 'GLY', 'LYS', 'GLY', 'THR', 'GLN', 'ALA', 'GLN',
       'PHE', 'ILE', 'MET', 'GLU', 'LYS', 'TYR', 'GLY', 'ILE', 'PRO',
       'GLN', 'ILE', 'SER', 'THR', 'GLY', 'ASP', 'MET', 'LEU', 'ARG',
       'ALA', 'ALA', 'VAL', 'LYS', 'SER', 'GLY', 'SER', 'GLU', 'LEU',
       'GLY', 'LYS', 'GLN', 'ALA', 'LYS', 'ASP', 'ILE', 'MET', 'ASP',
       'ALA', 'GLY', 'LYS', 'LEU', 'VAL', 'THR', 'ASP', 'GLU', 'LEU',
       'VAL', 'ILE', 'ALA', 'LEU', 'VAL', 'LYS', 'GLU', 'ARG', 'ILE',
       'ALA', 'GLN', 'GLU', 'ASP', 'CYS', 'ARG', 'ASN', 'GLY', 'PHE',
       'LEU', 'LEU', 'ASP', 'GLY', 'PHE', 'PRO', 'ARG', 'THR', 'ILE',
       'PRO', 'GLN', 'ALA', 'ASP', 'ALA', 'MET', 'LYS', 'GLU', 'ALA',
       'GLY', 'ILE', 'ASN', 'VAL', 'ASP', 'TYR', 'VAL', 'LEU', 'GLU',
       'PHE', 'ASP', 'VAL', 'PRO', 'ASP', 'GLU', 'LEU', 'ILE', 'VAL',
       'ASP', 'ARG', 'ILE', 'VAL', 'GLY', 'ARG', 'ARG', 'VAL', 'HSE',
       'ALA', 'PRO',

In [52]:
u.residues[u.residues.resnames == 'GLY'].n_residues

20

In [55]:
barray = u.residues.resnames == 'GLY'

In [57]:
barray.sum()

20

## Using coordinates

In [58]:
u.atoms.positions

AttributeError: 'AtomGroup' object has no attribute 'positions'

In [60]:
top = 'equilibrium/adk4AKE.psf'

In [59]:
traj = 'equilibrium/1ake_007-nowater-core-dt240ps.dcd'

In [61]:
u = mda.Universe(top, traj)

In [63]:
u.atoms.positions

array([[  2.87066364,  10.60445595,   9.75028801],
       [  3.10920501,  11.32470894,   9.0389967 ],
       [  3.74609542,  10.24300766,  10.17991066],
       ..., 
       [ -7.49935293,  10.89219856,  12.33476448],
       [ -6.59658432,  10.83427048,  12.92472839],
       [ -8.34826946,  10.59926796,  12.93470669]], dtype=float32)

### Challenge: calculate the center of geometry of the C$_\alpha$ atoms